# Generated by Django 5.2.6 on 2025-10-07 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='feedback',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='student_name',
        ),
        migrations.AddField(
            model_name='review',
            name='attendee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.attendee'),
            preserve_default=False,
        ),
    ]
