# Generated by Django 5.2.6 on 2025-10-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_rename_feedback_review_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
