# Generated by Django 5.2.6 on 2025-10-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_attendee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='place',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
