# Generated by Django 5.2.6 on 2025-10-14 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='class_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.classsession'),
        ),
    ]
