# Generated by Django 5.2.6 on 2025-10-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_attendee_class_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='quiz_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
