# Generated by Django 5.2.6 on 2025-10-16 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_question_question_type_response_text_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_answered_at', models.DateTimeField(auto_now=True)),
                ('is_fully_completed', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.attendee')),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.classsession')),
            ],
            options={
                'verbose_name_plural': 'Quiz Progress Records',
                'unique_together': {('attendee', 'class_session')},
            },
        ),
    ]
