# Generated by Django 5.2.6 on 2025-10-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_quizprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='session_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
