# Generated by Django 5.2.6 on 2025-10-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_classsession_session_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['email'], name='survey_atte_email_1c345c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['phone'], name='survey_atte_phone_05b7b6_idx'),
        ),
    ]
