# Generated by Django 5.2.6 on 2025-10-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_attendee_created_at_attendee_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('has_submitted', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_history', to='survey.attendee')),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='survey.classsession')),
            ],
            options={
                'verbose_name_plural': 'Session Attendances',
                'ordering': ['-joined_at'],
                'unique_together': {('attendee', 'class_session')},
            },
        ),
    ]
