# Generated by Django 5.2.6 on 2025-10-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_sessionattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='plain_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
