# Generated by Django 5.2.6 on 2025-10-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_hitcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='feedback_type',
            field=models.CharField(choices=[('quiz', 'Quiz Feedback'), ('review', 'General Review')], default='review', max_length=10),
        ),
    ]
